Feature/sqone 270/site footer
moderntribe/square-one pull request #1013
Opened 2022-07-01 19:13 UTC by dpellenwood

## What does this do/fix?

Builds out an MVP site footer. 🦶 

## QA

Links to relevant issues
- Footer: [SQONE-270](https://moderntribe.atlassian.net/browse/SQONE-270)
- Footer Nav: [SQONE-521](https://moderntribe.atlassian.net/browse/SQONE-521)

Links to deployed, scaffolded demo:
- [Link to Demo](https://example.com)

Screenshots/video:
- [Site Footer](http://p.tri.be/zdkR9u)

## Tests

Does this have tests?

- [ ] Yes
- [x] No, this doesn't need tests because it's boilerplate template development
- [ ] No, I need help figuring out how to write the tests.

2022-07-05 15:27 UTC, Vinsanity approved these changes
Looks good from my perspective Dave. GHA is yelling at you however. 😂

2022-07-08 13:55 UTC, ChrisMKindred approved these changes
👍

2022-07-08 14:54 UTC, lindseyolson approved these changes

2022-07-20 15:32 UTC, Vinsanity approved these changes
Nice work here Davee! Is this something Design is already aware of or we this informed by something they already provided?

2022-07-20 16:09 UTC, defunctl requested changes

2022-07-20 18:57 UTC, dpellenwood commented
> Nice work here Davee! Is this something Design is already aware of or we this informed by something they already provided?

Yep. It's already in the [SquareOne Figma](https://www.figma.com/file/Wj2g7HVyBQWYIuxgNKMCxf/SQ1-Main-Patterns?node-id=5417%3A6431) file. ;)

2022-07-22 20:13 UTC, ChrisMKindred approved these changes

2022-07-23 22:58 UTC, defunctl commented on wp-content/themes/core/components/site_footer/Site_Footer_Controller.php
> +		return file_exists( $image_path ) ? file_get_contents( $image_path ) : '';
@dpellenwood what we should do is that just after this is image is uploaded, capture its source then (one time) and save it to the options table. Any time you need the source, fetch it using get_option() instead and also probably a good idea to run it through the SVG sanitization library we have in tribe libs once more before displaying it

2022-07-25 19:29 UTC, dpellenwood commented on wp-content/themes/core/components/site_footer/Site_Footer_Controller.php
> +		return file_exists( $image_path ) ? file_get_contents( $image_path ) : '';
Thanks Justin. Chatted w/ Chris about this and decided to pull it from the Footer. We'll just render the SVG as an image for default SquareOne. If a project needs something more complex, we can handle it then.

2022-07-25 20:33 UTC, merged