Block middleware: Post Loop Field
moderntribe/square-one pull request #1018
Opened 2022-07-08 20:50 UTC by defunctl

## What does this do/fix?

- WIP

## QA

Links to relevant issues
- [Link to Issue](https://example.com)

Links to deployed, scaffolded demo:
- [Link to Demo](https://example.com)

Screenshots/video:
- [Link to Video](https://example.com)

## Tests

Does this have tests?

- [ ] Yes
- [ ] No, this doesn't need tests because...
- [ ] No, I need help figuring out how to write the tests.

2022-07-26 14:32 UTC, dpellenwood approved these changes
I love this, Justin! Thank you for tackling this beast. A couple thoughts:

1. I think it would be good to get design/strategy input on the field UX as they might have some suggestions for making it easier to view. Similar to how we did some field type changes and style hacking with the plugin version, we could do similar here. I'll make mention this to Sarah and see if she has space to do a review.
1. Very much thinking aloud: I wonder if we could package this up somehow to make it public as an alternative to the WP Core Query block. I realize this is probably a step backwards for our own blocks system as it benefits from the Middleware system as a whole. But, it's such a powerful tool for handling custom queries as a user.

2022-07-27 17:24 UTC, ChrisMKindred requested changes
Great work @defunctl.  The only changes I have are to align the field labels with the updates with #1011

2022-07-27 17:24 UTC, ChrisMKindred commented on wp-content/plugins/core/src/Blocks/Middleware/Post_Loop/Field_Middleware/Post_Loop_Field_Middleware.php
> +			'label'             => esc_html__( 'Build your query', 'tribe' ),
```suggestion
			'label'             => esc_html__( 'Build Your Query', 'tribe' ),
```

2022-07-27 17:24 UTC, ChrisMKindred commented on wp-content/plugins/core/src/Blocks/Middleware/Post_Loop/Field_Middleware/Post_Loop_Field_Middleware.php
> +			'label'         => esc_html__( 'Order by', 'tribe' ),
```suggestion
			'label'         => esc_html__( 'Order By', 'tribe' ),
```

2022-07-27 17:24 UTC, ChrisMKindred commented on wp-content/plugins/core/src/Blocks/Middleware/Post_Loop/Field_Middleware/Post_Loop_Field_Middleware.php
> +				self::OPTION_TITLE => esc_html__( 'Post title', 'tribe' ),
```suggestion
				self::OPTION_DATE  => esc_html__( 'Post Date', 'tribe' ),
				self::OPTION_TITLE => esc_html__( 'Post Title', 'tribe' ),
```

2022-07-27 17:24 UTC, ChrisMKindred commented on wp-content/plugins/core/src/Blocks/Middleware/Post_Loop/Field_Middleware/Post_Loop_Field_Middleware.php
> +				'label'         => sprintf( esc_html__( 'Filter by %s', 'tribe' ), $label ),
```suggestion
				'label'         => sprintf( esc_html__( 'Filter By %s', 'tribe' ), $label ),
```

2022-07-27 17:24 UTC, ChrisMKindred commented on wp-content/plugins/core/src/Blocks/Middleware/Post_Loop/Field_Middleware/Post_Loop_Field_Middleware.php
> +			'instructions'      => esc_html__( 'Set or override the post date', 'tribe' ),
```suggestion
			'instructions'      => esc_html__( 'Set or override the post date.', 'tribe' ),
```

2022-07-27 17:24 UTC, ChrisMKindred commented on wp-content/plugins/core/src/Blocks/Middleware/Post_Loop/Field_Middleware/Post_Loop_Field_Middleware.php
> +			'instructions'      => esc_html__( 'Set or override the post author', 'tribe' ),
```suggestion
			'instructions'      => esc_html__( 'Set or override the post author.', 'tribe' ),
```

2022-07-27 17:24 UTC, ChrisMKindred commented on wp-content/plugins/core/src/Blocks/Middleware/Post_Loop/Field_Middleware/Post_Loop_Field_Middleware.php
> +			'instructions'      => esc_html__( 'Set or override the primary post category', 'tribe' ),
```suggestion
			'instructions'      => esc_html__( 'Set or override the primary post category.', 'tribe' ),
```

2022-07-27 17:24 UTC, ChrisMKindred commented on wp-content/plugins/core/src/Blocks/Types/Card_Grid/Card_Grid.php
> +				],
Remove hidden labels.
```suggestion
```

2022-07-27 17:24 UTC, ChrisMKindred commented on wp-content/plugins/core/src/Blocks/Types/Card_Grid/Card_Grid.php
> +				'label'   => esc_html__( 'Leadin', 'tribe' ),
```suggestion
				'label'   => esc_html__( 'Overline', 'tribe' ),
```

2022-08-08 15:28 UTC, merged