Replace Configure SMTP plugin with WP Mail SMTP
moderntribe/square-one pull request #1033
Opened 2022-08-10 20:13 UTC by tarecord

## What does this do/fix?

On a current project Configure SMTP throws errors with every request and ends up triggering the Whoops UI, making local development a pain. This swaps that plugin (which was [last updated 11 years ago](https://wordpress.org/plugins/configure-smtp/)) with [a plugin that is actively maintained](https://wordpress.org/plugins/wp-mail-smtp/) and offers a lot of functionality.

2022-08-10 20:36 UTC, ChrisMKindred commented
@tarecord I like that configure SMTP doesn't try to throw a pro version in your face or take up space in the main WP Nav.  What is the error that is getting thrown?

2022-08-10 21:40 UTC, defunctl commented on composer.json
> +    "wpackagist-plugin/wp-mail-smtp": "^3.5",
@tarecord I know you didn't ask for my review, but you should add the specific version for plugins so during deploys a new version doesn't just get randomly installed without being tested.

2022-08-10 21:49 UTC, dpellenwood commented
Just a thought...do we _need_ to require a SMTP plugin by-default in SquareOne?

2022-08-10 21:51 UTC, ChrisMKindred commented
> @dpellenwood  Just a thought...do we need to require a SMTP plugin by default in SquareOne?
No

2022-08-10 21:52 UTC, defunctl commented
> Just a thought...do we _need_ to require a SMTP plugin by default in SquareOne?

Probably not, nope.

2022-08-11 13:30 UTC, tarecord commented
> Just a thought...do we need to require a SMTP plugin by default in SquareOne?

That's what I'm thinking. I figured having a concrete PR to bubble up discussion would be good :)

@ChrisMKindred I'm seeing this when its activated:
```
Declaration of c2c_ConfigureSMTP::options_page_description() should be compatible with C2C_Plugin_023::options_page_description($localized_heading_text = '')
```

@dpellenwood if I pull out the default, do we have a list of recommended SMTP plugins?

2022-08-11 13:38 UTC, dpellenwood commented
> @dpellenwood if I pull out the default, do we have a list of recommended SMTP plugins?

I generally point client's to their hosting provider's recommendation for email/SMTP. Here is [Pantheon's](https://pantheon.io/docs/email) and [WP Engine's](https://wpengine.com/support/using-3rd-party-email-provider-send-mail-wordpress/). In short, (in order of recommendation), I would say:
1. [MailGun](https://wpengine.com/support/configuring-mailgun-for-wordpress/) another providers which supports API-based connections
2. [WP Mail SMTP](https://wordpress.org/plugins/wp-mail-smtp/) for a true SMTP connection. (Recommended by both Pantheon & WPE.)

2022-08-18 13:12 UTC, ChrisMKindred requested changes
Let's just remove the plugin. Each site has its own unique email needs (MailGun, SMTP, Hosting requirements, etc...), and the decision should be based on that. We also have documentation that provides a list of plugins we recommend using for those situations.

2022-09-15 14:01 UTC, dpellenwood commented
> Let's just remove the plugin. Each site has its own unique email needs (MailGun, SMTP, Hosting requirements, etc...), and the decision should be based on that. We also have documentation that provides a list of plugins we recommend using for those situations.

@tarecord , curious if you'd have a chance to get back to this update the PR to remove this plugin from our default composer?

2022-09-15 15:13 UTC, tarecord commented
> @tarecord, curious if you'd have a chance to get back to this update the PR to remove this plugin from our default composer?

@dave, this should be good to go now.

2022-09-15 20:01 UTC, dpellenwood approved these changes
Looks good Tanner, just a changelog entry then you can merge. Thanks!

2022-09-30 21:17 UTC, ChrisMKindred approved these changes
👍 Looks good, thanks!

2022-10-04 18:52 UTC, merged