[WIP] Use New WP_ENVIRONMENT_TYPE Constant for Site Environment
moderntribe/square-one pull request #703
Opened 2021-04-20 14:25 UTC by tarecord

## What does this do/fix?

[SQONE-456](https://moderntribe.atlassian.net/browse/SQONE-456?atlOrigin=eyJpIjoiOGI2Nzk4ZTAzNTMyNDdlZThlNTc0ZmIzNjI2MzJhMGMiLCJwIjoiaiJ9)

Updates the method for checking the current site environment to use the `WP_ENVIRONMENT_TYPE` constant [added in Core v5.5](https://make.wordpress.org/core/2020/07/24/new-wp_get_environment_type-function-in-wordpress-5-5/).

## Tests

Does this have tests?

- [ ] Yes
- [ ] No, this doesn't need tests because...
- [x] No, I need help figuring out how to write the tests.

2021-04-20 17:06 UTC, defunctl requested changes
Also check the `.github/workflows` folder that references the old defines as well as in the README.md

2021-04-21 15:06 UTC, tarecord commented on wp-config-environment.php
> +if ( defined( 'WP_ENVIRONMENT_TYPE' ) && WP_ENVIRONMENT_TYPE === 'production' ) {
Good insight, I've updated the references.

2021-04-21 15:07 UTC, tarecord commented
Good insight, references in `.github/workflows` have been updated.

2021-04-26 15:29 UTC, nickpelton commented
Looks like a good conversion. Only note, we may want to set the new key and the old key JIC any of our external tools, like TribeLibs references the old global as well.

2021-04-27 13:27 UTC, tarecord commented
Does the `local-config.php` ever make it to the server, or is it only for local environments? I was thinking we could define them there as defaults:

```php
/**
 * Set the current environment type. Accepted values:
 * - production (default)
 * - staging
 * - development
 * - local
 *
 * @link https://make.wordpress.org/core/2020/07/24/new-wp_get_environment_type-function-in-wordpress-5-5/
 */
define( 'WP_ENVIRONMENT_TYPE', 'development' );

// Fallback for older environments.
define ( 'ENVIRONMENT', 'DEV' );
```

2021-04-27 13:43 UTC, nickpelton commented
It depends on who the host because we don't know how they treat the wp-config.php. In general we either use the .env, local-config.php, or other environment var setting tools. I'd say 70% of the time, we generate a local-config.php. If you look in the GHA deploy script you'll see we generate one on a deploy.

2021-04-27 19:50 UTC, nickpelton commented
A link to where we create the local-config.php on a deploy https://github.com/moderntribe/square-one/blob/main/.github/workflows/deploy-dev.yml#L65

2021-05-03 19:10 UTC, merged