Add PHP Storm phpcs instructions
moderntribe/square-one pull request #776
Opened 2021-06-04 16:49 UTC by verytwisty

writing up slack conversation with Justin

## What does this do/fix?

Adds documentation for setting up PHPCS with PHP Strom

## Tests

Does this have tests?

- [ ] Yes
- [x ] No, this doesn't need tests because it's documentation
- [ ] No, I need help figuring out how to write the tests.

2021-06-04 16:55 UTC, defunctl requested changes
Couple of changes, would like screenshots at some point but this is still way better than a TODO :)

2021-06-04 16:55 UTC, defunctl commented on docs/tooling/phpcs.md
> +## Make sure project won't commit with errors
Can instead link all of this to https://github.com/moderntribe/square-one/blob/main/docs/tooling/git-hooks.md#automatic-git-hooks so we don't have to maintain the same document in two places.

2021-06-04 16:55 UTC, defunctl commented on docs/tooling/phpcs.md
> +3. In the PHP_CodeSniffer dialog that opens, go to: `project-folder/bin/`
```suggestion
3. In the PHP_CodeSniffer dialog that opens, go to: `project-folder/vendor/bin/`
```

2021-06-04 16:55 UTC, defunctl commented on docs/tooling/phpcs.md
> +9. click the `...` button to open a dialogue box to select the `phpcs.xml.dist` in the root of the square one directory
Would add another step here to only tell it to check `php` extensions, by removing the `js,css` ones.

2021-06-07 08:50 UTC, verytwisty commented
@defunctl made those changes and added some images :-)

2021-06-08 19:18 UTC, nickpelton approved these changes
Docs! ❤️  🚀

2021-06-08 21:53 UTC, defunctl approved these changes
Looks great! :rocket:

2021-06-09 15:44 UTC, merged