SQONE-667:
moderntribe/square-one pull request #868
Opened 2021-09-13 18:31 UTC by dpellenwood

Bugfix for editor styles regression due to reset.css enqueued in the block editor in version 5.8 of WordPress Core.

## QA

Links to relevant issues
- [Link to Issue](https://moderntribe.atlassian.net/browse/SQONE-667)

## Tests

Does this have tests?

- [ ] Yes
- [x] No, this doesn't need tests because it's a bugfix applied to WP Core.
- [ ] No, I need help figuring out how to write the tests.

2021-09-13 20:18 UTC, Vinsanity approved these changes
🥇 🩹   Nice work DAVEEEEEEE! thanks for this interim fix.

2021-09-13 20:46 UTC, defunctl requested changes
Thanks so much for solving this :taco:

2021-09-13 20:46 UTC, defunctl commented on wp-content/plugins/core/src/Assets/Admin/Styles.php
> +		if ( ! isset( wp_styles()->registered['wp-edit-blocks'] ) ) {
```suggestion
		if ( ! isset( wp_styles()->registered['wp-edit-blocks']->deps ) ) {
```

Would feel much more comfortable checking for the exact property in the edge case WordPress has `registered['wp-edit-blocks']` set but not `registered['wp-edit-blocks']->deps`

2021-09-13 20:46 UTC, defunctl commented on wp-content/plugins/core/src/Assets/Admin/Styles.php
> +	 * See https://github.com/WordPress/gutenberg/pull/33522 for context.
```suggestion
	 * @link https://github.com/WordPress/gutenberg/pull/33522 for context.
```

2021-09-14 14:40 UTC, dpellenwood commented
@defunctl, Committed your suggestions. want to give this another look-see?

2021-09-14 14:49 UTC, defunctl approved these changes
Looks great

2021-09-14 14:52 UTC, merged